; PlatformIO Project Configuration
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = main
